name: exercises-for-programmer-in-haskell
version: 0.1.0.0
github: "your/repo"
license: MIT
author: "Yasuyuki Abe"
maintainer: "yasu@yasuabe.net"
extra-source-files: []

dependencies:
  - base >= 4.7 && < 5
  - string-interpolate
  - transformers
  - scotty
  - lucid
  - text
  - aeson
  - aeson-casing
  - bytestring
  - directory
  - gi-gtk
  - gi-gdkpixbuf
  - gi-gio
  - http-conduit
  - http-client
  - http-client-tls
  - time
  - regex-tdfa
  - exceptions
  - haskeline
  - random
  - mtl
  - unordered-containers
  - extra
  - validation
  - containers
  - conduit
  - conduit-extra
  - hashtables
  - hedis
  - resource-pool
  - yesod
  - yesod-core
  - yesod-form
  - shakespeare
  - template-haskell 
  - persistent
  - persistent-mongoDB
  - mongoDB
  - memory 
  - uuid
  - cryptohash-md5
  - base16-bytestring
  - beam-core
  - beam-sqlite
  - sqlite-simple
  - servant
  - servant-server
  - wai
  - warp
  - wai-cors
  - network-uri
  - streamly-core

library:
  source-dirs: src
  exposed-modules:
    - Common.App
    - Common.Function
    - Common.System
    - Common.Util
    - Common.Math
  ghc-options: -Wall

executables:
  ex01:
    main: Main.hs
    source-dirs: ex01
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex02:
    main: Main.hs
    source-dirs: ex02
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex03:
    main: Main.hs
    source-dirs: ex03
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex06:
    main: Main.hs
    source-dirs: ex06
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell
      - time

  ex07:
    main: Main.hs
    source-dirs: ex07
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex08:
    main: Main.hs
    source-dirs: ex08
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex10:
    main: Main.hs
    source-dirs: ex10
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex13:
    main: Main.hs
    source-dirs: ex13
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex14:
    main: Main.hs
    source-dirs: ex14
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex18:
    main: Main.hs
    source-dirs: ex18
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex23:
    main: Main.hs
    source-dirs: ex23
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex24:
    main: Main.hs
    source-dirs: ex24
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex27:
    main: Main.hs
    source-dirs: ex27
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex28:
    main: Main.hs
    source-dirs: ex28
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex30:
    main: Main.hs
    source-dirs: ex30
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex32:
    main: Main.hs
    source-dirs: ex32
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex33:
    main: Main.hs
    source-dirs: ex33
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex38:
    main: Main.hs
    source-dirs: ex38
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex40:
    main: Main.hs
    source-dirs: ex40
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex41:
    main: Main.hs
    source-dirs: ex41
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex42:
    main: Main.hs
    source-dirs: ex42
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex46:
    main: Main.hs
    source-dirs: ex46
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex49:
    main: Main.hs
    source-dirs: ex49
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - exercises-for-programmer-in-haskell
      - gi-gtk
      - haskell-gi-base
      - gi-gio
      - gi-gdkpixbuf
      - gi-glib
      - http-client
      - aeson
      - bytestring
      - text

  ex51:
    main: Main.hs
    source-dirs: ex51
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex52:
    main: Main.hs
    source-dirs: ex52/Server
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex52-client:
    main: Main.hs
    source-dirs: ex52/Client
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex53:
    main: Main.hs
    source-dirs: ex53
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex54:
    main: Main.hs
    source-dirs: ex54
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex55:
    main: Main.hs
    source-dirs: ex55
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell
    extra-source-files:
      - ex55/templates/*.hamlet

  ex56:
    main: Main.hs
    source-dirs: ex56
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex57:
    main: Main.hs
    source-dirs: ex57
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

tests:
  ex03-test:
    main: Spec.hs
    source-dirs:
      - test/ex03
      - ex03
    dependencies:
      - base
      - QuickCheck
      - HUnit
      - exercises-for-programmer-in-haskell

  ex07-test:
    main: Spec.hs
    source-dirs:
      - test/ex07
      - ex07
    dependencies:
      - base
      - QuickCheck
      - exercises-for-programmer-in-haskell

  ex13-test:
    main: Spec.hs
    source-dirs:
      - test/ex13
      - ex13
    dependencies:
      - base
      - QuickCheck
      - exercises-for-programmer-in-haskell

  ex24-test:
    main: Spec.hs
    source-dirs:
      - test/ex24
      - ex24
    dependencies:
      - base
      - QuickCheck
      - exercises-for-programmer-in-haskell

  ex27-test:
    main: Spec.hs
    source-dirs:
      - test/ex27
      - ex27
    dependencies:
      - base
      - HUnit
      - exercises-for-programmer-in-haskell

  ex40-test:
    main: Test.hs
    source-dirs:
      - test/ex40
      - ex40
    dependencies:
      - base
      - QuickCheck >= 2.14
      - quickcheck-classes >= 0.6
      - quickcheck-classes-base >= 0.6
      - exercises-for-programmer-in-haskell

  ex51-test:
    main: Test.hs
    source-dirs:
      - test/ex51
      - ex51
    dependencies:
      - base
      - HUnit
      - exercises-for-programmer-in-haskell

  ex53-test:
    main: Test.hs
    source-dirs:
      - test/ex53
      - ex53
    dependencies:
      - base
      - HUnit
      - exercises-for-programmer-in-haskell
