name: exercises-for-programmer-in-haskell
version: 0.1.0.0
github: "your/repo"
license: MIT
author: "Yasuyuki Abe"
maintainer: "yasu@yasuabe.net"
extra-source-files: []

dependencies:
  - base >= 4.7 && < 5
  - string-interpolate
  - transformers
  - scotty
  - lucid
  - text
  - aeson
  - aeson-casing
  - bytestring
  - directory
  - gi-gtk
  - gi-gdkpixbuf
  - gi-gio
  - http-conduit
  - http-client
  - http-client-tls
  - time
  - regex-tdfa
  - exceptions
  - haskeline
  - random
  - mtl
  - unordered-containers
  - extra

library:
  source-dirs: src
  exposed-modules:
    - Common.App
    - Common.Function
    - Common.System
    - Common.Util
  ghc-options: -Wall

executables:
  ex01:
    main: Main.hs
    source-dirs: ex01
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex02:
    main: Main.hs
    source-dirs: ex02
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex03:
    main: Main.hs
    source-dirs: ex03
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex06:
    main: Main.hs
    source-dirs: ex06
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell
      - time

  ex07:
    main: Main.hs
    source-dirs: ex07
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex13:
    main: Main.hs
    source-dirs: ex13
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex14:
    main: Main.hs
    source-dirs: ex14
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex23:
    main: Main.hs
    source-dirs: ex23
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex24:
    main: Main.hs
    source-dirs: ex24
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex28:
    main: Main.hs
    source-dirs: ex28
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex33:
    main: Main.hs
    source-dirs: ex33
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex41:
    main: Main.hs
    source-dirs: ex41
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex49:
    main: Main.hs
    source-dirs: ex49
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - exercises-for-programmer-in-haskell
      - gi-gtk
      - haskell-gi-base
      - gi-gio
      - gi-gdkpixbuf
      - gi-glib
      - http-client
      - aeson
      - bytestring
      - text

  ex51:
    main: Main.hs
    source-dirs: ex51
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

  ex56:
    main: Main.hs
    source-dirs: ex56
    ghc-options: -Wall
    dependencies:
      - exercises-for-programmer-in-haskell

tests:
  ex03-test:
    main: Spec.hs
    source-dirs:
      - test/ex03
      - ex03
    dependencies:
      - base
      - QuickCheck
      - HUnit
      - exercises-for-programmer-in-haskell

  ex07-test:
    main: Spec.hs
    source-dirs:
      - test/ex07
      - ex07
    dependencies:
      - base
      - QuickCheck
      - exercises-for-programmer-in-haskell

  ex13-test:
    main: Spec.hs
    source-dirs:
      - test/ex13
      - ex13
    dependencies:
      - base
      - QuickCheck
      - exercises-for-programmer-in-haskell

  ex24-test:
    main: Spec.hs
    source-dirs:
      - test/ex24
      - ex24
    dependencies:
      - base
      - QuickCheck
      - exercises-for-programmer-in-haskell

  ex51-test:
    main: Test.hs
    source-dirs:
      - test/ex51
      - ex51
    dependencies:
      - base
      - HUnit
      - exercises-for-programmer-in-haskell